version: '3'
services:
  pdf-compose-service:
    build:
      context: server
    ports:
        - "50051:50051"
  controller-service:
    build:
      context: controller
    ports:
        - "8080:8080"
