// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.13.0
// source: server/api/api.proto

package pdfcompose

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Chunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content []byte `protobuf:"bytes,1,opt,name=Content,proto3" json:"Content,omitempty"`
}

func (x *Chunk) Reset() {
	*x = Chunk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_api_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunk) ProtoMessage() {}

func (x *Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chunk.ProtoReflect.Descriptor instead.
func (*Chunk) Descriptor() ([]byte, []int) {
	return file_server_api_api_proto_rawDescGZIP(), []int{0}
}

func (x *Chunk) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type FormData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Upfile1 []byte `protobuf:"bytes,1,opt,name=upfile1,proto3" json:"upfile1,omitempty"`
	Upfile2 []byte `protobuf:"bytes,2,opt,name=upfile2,proto3,oneof" json:"upfile2,omitempty"`
	Upfile3 []byte `protobuf:"bytes,3,opt,name=upfile3,proto3,oneof" json:"upfile3,omitempty"`
}

func (x *FormData) Reset() {
	*x = FormData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_api_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FormData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormData) ProtoMessage() {}

func (x *FormData) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormData.ProtoReflect.Descriptor instead.
func (*FormData) Descriptor() ([]byte, []int) {
	return file_server_api_api_proto_rawDescGZIP(), []int{1}
}

func (x *FormData) GetUpfile1() []byte {
	if x != nil {
		return x.Upfile1
	}
	return nil
}

func (x *FormData) GetUpfile2() []byte {
	if x != nil {
		return x.Upfile2
	}
	return nil
}

func (x *FormData) GetUpfile3() []byte {
	if x != nil {
		return x.Upfile3
	}
	return nil
}

type File struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	File []byte `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
}

func (x *File) Reset() {
	*x = File{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_api_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_server_api_api_proto_rawDescGZIP(), []int{2}
}

func (x *File) GetFile() []byte {
	if x != nil {
		return x.File
	}
	return nil
}

var File_server_api_api_proto protoreflect.FileDescriptor

var file_server_api_api_proto_rawDesc = []byte{
	0x0a, 0x14, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x70, 0x69,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x70, 0x64, 0x66, 0x63, 0x6f, 0x6d, 0x70, 0x6f,
	0x73, 0x65, 0x22, 0x21, 0x0a, 0x05, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x43,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x43, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x7a, 0x0a, 0x08, 0x46, 0x6f, 0x72, 0x6d, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x70, 0x66, 0x69, 0x6c, 0x65, 0x31, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x07, 0x75, 0x70, 0x66, 0x69, 0x6c, 0x65, 0x31, 0x12, 0x1d, 0x0a, 0x07, 0x75,
	0x70, 0x66, 0x69, 0x6c, 0x65, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x07,
	0x75, 0x70, 0x66, 0x69, 0x6c, 0x65, 0x32, 0x88, 0x01, 0x01, 0x12, 0x1d, 0x0a, 0x07, 0x75, 0x70,
	0x66, 0x69, 0x6c, 0x65, 0x33, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x01, 0x52, 0x07, 0x75,
	0x70, 0x66, 0x69, 0x6c, 0x65, 0x33, 0x88, 0x01, 0x01, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x75, 0x70,
	0x66, 0x69, 0x6c, 0x65, 0x32, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x75, 0x70, 0x66, 0x69, 0x6c, 0x65,
	0x33, 0x22, 0x1a, 0x0a, 0x04, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x69, 0x6c,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x32, 0x48, 0x0a,
	0x11, 0x50, 0x64, 0x66, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x33, 0x0a, 0x04, 0x53, 0x65, 0x6e, 0x64, 0x12, 0x14, 0x2e, 0x70, 0x64, 0x66,
	0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x65, 0x2e, 0x46, 0x6f, 0x72, 0x6d, 0x44, 0x61, 0x74, 0x61,
	0x1a, 0x11, 0x2e, 0x70, 0x64, 0x66, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x65, 0x2e, 0x43, 0x68,
	0x75, 0x6e, 0x6b, 0x22, 0x00, 0x30, 0x01, 0x42, 0x20, 0x5a, 0x1e, 0x63, 0x6f, 0x6d, 0x70, 0x6f,
	0x73, 0x65, 0x72, 0x2f, 0x70, 0x64, 0x66, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x65, 0x3b, 0x70,
	0x64, 0x66, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_server_api_api_proto_rawDescOnce sync.Once
	file_server_api_api_proto_rawDescData = file_server_api_api_proto_rawDesc
)

func file_server_api_api_proto_rawDescGZIP() []byte {
	file_server_api_api_proto_rawDescOnce.Do(func() {
		file_server_api_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_server_api_api_proto_rawDescData)
	})
	return file_server_api_api_proto_rawDescData
}

var file_server_api_api_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_server_api_api_proto_goTypes = []interface{}{
	(*Chunk)(nil),    // 0: pdfcompose.Chunk
	(*FormData)(nil), // 1: pdfcompose.FormData
	(*File)(nil),     // 2: pdfcompose.File
}
var file_server_api_api_proto_depIdxs = []int32{
	1, // 0: pdfcompose.PdfComposeService.Send:input_type -> pdfcompose.FormData
	0, // 1: pdfcompose.PdfComposeService.Send:output_type -> pdfcompose.Chunk
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_server_api_api_proto_init() }
func file_server_api_api_proto_init() {
	if File_server_api_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_server_api_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Chunk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_api_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FormData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_api_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*File); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_server_api_api_proto_msgTypes[1].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_server_api_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_api_api_proto_goTypes,
		DependencyIndexes: file_server_api_api_proto_depIdxs,
		MessageInfos:      file_server_api_api_proto_msgTypes,
	}.Build()
	File_server_api_api_proto = out.File
	file_server_api_api_proto_rawDesc = nil
	file_server_api_api_proto_goTypes = nil
	file_server_api_api_proto_depIdxs = nil
}
