// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.13.0
// source: server/api/api.proto

package pdfcompose

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PdfComposeService_Send_FullMethodName = "/pdfcompose.PdfComposeService/Send"
)

// PdfComposeServiceClient is the client API for PdfComposeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PdfComposeServiceClient interface {
	Send(ctx context.Context, in *FormData, opts ...grpc.CallOption) (PdfComposeService_SendClient, error)
}

type pdfComposeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPdfComposeServiceClient(cc grpc.ClientConnInterface) PdfComposeServiceClient {
	return &pdfComposeServiceClient{cc}
}

func (c *pdfComposeServiceClient) Send(ctx context.Context, in *FormData, opts ...grpc.CallOption) (PdfComposeService_SendClient, error) {
	stream, err := c.cc.NewStream(ctx, &PdfComposeService_ServiceDesc.Streams[0], PdfComposeService_Send_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &pdfComposeServiceSendClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PdfComposeService_SendClient interface {
	Recv() (*Chunk, error)
	grpc.ClientStream
}

type pdfComposeServiceSendClient struct {
	grpc.ClientStream
}

func (x *pdfComposeServiceSendClient) Recv() (*Chunk, error) {
	m := new(Chunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PdfComposeServiceServer is the server API for PdfComposeService service.
// All implementations must embed UnimplementedPdfComposeServiceServer
// for forward compatibility
type PdfComposeServiceServer interface {
	Send(*FormData, PdfComposeService_SendServer) error
	mustEmbedUnimplementedPdfComposeServiceServer()
}

// UnimplementedPdfComposeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPdfComposeServiceServer struct {
}

func (UnimplementedPdfComposeServiceServer) Send(*FormData, PdfComposeService_SendServer) error {
	return status.Errorf(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedPdfComposeServiceServer) mustEmbedUnimplementedPdfComposeServiceServer() {}

// UnsafePdfComposeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PdfComposeServiceServer will
// result in compilation errors.
type UnsafePdfComposeServiceServer interface {
	mustEmbedUnimplementedPdfComposeServiceServer()
}

func RegisterPdfComposeServiceServer(s grpc.ServiceRegistrar, srv PdfComposeServiceServer) {
	s.RegisterService(&PdfComposeService_ServiceDesc, srv)
}

func _PdfComposeService_Send_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FormData)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PdfComposeServiceServer).Send(m, &pdfComposeServiceSendServer{stream})
}

type PdfComposeService_SendServer interface {
	Send(*Chunk) error
	grpc.ServerStream
}

type pdfComposeServiceSendServer struct {
	grpc.ServerStream
}

func (x *pdfComposeServiceSendServer) Send(m *Chunk) error {
	return x.ServerStream.SendMsg(m)
}

// PdfComposeService_ServiceDesc is the grpc.ServiceDesc for PdfComposeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PdfComposeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pdfcompose.PdfComposeService",
	HandlerType: (*PdfComposeServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Send",
			Handler:       _PdfComposeService_Send_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "server/api/api.proto",
}
