// Code generated by go-swagger; DO NOT EDIT.

package main

import (
	"fmt"
	"net"
	"service-pdf-compose/pkg/composer/pdfcompose"

	"service-pdf-compose/internal/handler"

	"google.golang.org/grpc"
)

// This file was generated by the swagger tool.
// Make sure not to overwrite this file after you generated it because all your edits would be lost!

func main() {
	fmt.Println("Starting server ...")
	lis, err := net.Listen("tcp", ":50051")
	if err != nil {
		panic(err)
	}
	s := grpc.NewServer()
	server := &handler.PdfComposeServiceClient{}
	pdfcompose.RegisterPdfComposeServiceServer(s, server)
	if err := s.Serve(lis); err != nil {
		panic(err)
	}

}
